### ISSUE TITLE
zero demo 在 node 里面安装之后，无法启动，需要排查一下原因

### ISSUE THREAD

**Issue by NateRobinson** [blocklet/zero-demo#7]

**Comment by NateRobinson** [comment]
[2021-02-26 15:47:49] [error] [@abtnode/core:blocklet:manager] "check blocklet if started failed" {"did":"z8iZvUKWGvDyi8Woc886fErHrfFrAVRFGUgeE","appId":"zero-demo","ports":{"PORT":8095},"context":{"protocol":"http","user":{"type":"profile","fullName":"nate","email":"840501291@qq.com","did":"z1eezb8uSpFg2itN5A4minhTA1fSWmGyEfQ","pk":"z8YsPPB5DzYRv7LBt5nFAS4tZUwUpm6aN7JPErYZatTsm","role":"owner","approved":true,"_id":"8Qd1SLsj2VZtPDiz","createdAt":"2021-02-26T00:20:19.333Z","updatedAt":"2021-02-26T00:20:19.333Z","bid":null},"url":"/api/gql","query":{},"hostname":"192.168.2.4","port":0},"timeout":60000,"error":"the service is not ready within 55 seconds, please check your network","error_stack":"Error: the service is not ready within 55 seconds, please check your network\n    at ensureStarted (/Users/naterobinson/work/arcblock/abt-node/core/util/lib/ensure-endpoint-healthy.js:25:13)\n    at async /Users/naterobinson/work/arcblock/abt-node/core/util/lib/ensure-endpoint-healthy.js:66:5\n    at async /Users/naterobinson/work/arcblock/abt-node/core/util/lib/try-with-timeout.js:13:22"}

**Comment by NateRobinson** [comment]
https://github.com/ArcBlock/abt-node/issues/2423

**Comment by polunzh** [comment]
zero 版本: 1.1.22
